# Generated by Django 4.1.6 on 2023-08-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_product_author_product_created_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
