# Generated by Django 4.1.6 on 2023-08-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_hom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hom',
        ),
    ]
